## Create numpy arrays "array like" data type

In [1]:
import numpy as np

In [39]:
# printing the verion

print(np.__version__)
a = np.ones(1)
a

1.17.2


array([1.])

## array()

In [40]:
# create a 1D numpy array

my_1D_array = np.array([-11,28,3,49, 66])
my_1D_array

array([-11,  28,   3,  49,  66])

In [41]:
# create a 2D numpy array

my_2D_array = np.array([[12,34,65], [87,3,1,]])
my_2D_array

array([[12, 34, 65],
       [87,  3,  1]])

In [42]:
# to access the elemenet from an array.
# print out the first element from the array

my_1D_array[0]

-11

In [43]:
# print out the last element of the array

my_1D_array[-1]

66

In [44]:
# change the element in the array
my_1D_array[0] = 200
print(my_1D_array)

[200  28   3  49  66]


In [45]:
# convert python tuple to npmpy arrary
# by default array will be of float type, we can convert it to int with the dtype

py_tuple = (12,23.5, 55, 10)
nd_array = np.array(py_tuple, dtype="int")
print("this is nd array -> ",nd_array, type(nd_array))

this is nd array ->  [12 23 55 10] <class 'numpy.ndarray'>


In [46]:
# covert list to ndarray

my_list = [[12,5,3,67, -12], [98,65, 0, 3, 44]]
list_to_np_array = np.array(my_list)
print('ndarray', list_to_np_array)

ndarray [[ 12   5   3  67 -12]
 [ 98  65   0   3  44]]


## Intrinsic Numpy array creation using numpy methods

## arange()

In [47]:
# Arange will generate an array upto the given number
# syntax(start,stop, step) 
# only start

print('with only start ->', np.arange(10))
print('wiht start and end ->', np.arange(10, 20))
print('wiht start, end and number of steps ->', np.arange(1, 10, 2))

with only start -> [0 1 2 3 4 5 6 7 8 9]
wiht start and end -> [10 11 12 13 14 15 16 17 18 19]
wiht start, end and number of steps -> [1 3 5 7 9]


In [48]:
# arithmetic operation in the numpy array

arange_array = np.arange(1,20,2)

print('addition->',arange_array + 10)
print('multiplication->', arange_array * 2)
print('division->',arange_array / 4)

addition-> [11 13 15 17 19 21 23 25 27 29]
multiplication-> [ 2  6 10 14 18 22 26 30 34 38]
division-> [0.25 0.75 1.25 1.75 2.25 2.75 3.25 3.75 4.25 4.75]


In [49]:
# get the length of the array in two different ways

print('numPY array size->',len(arange_array))
print('numPY array size->',arange_array.size)

numPY array size-> 10
numPY array size-> 10


## linspace()

In [50]:
## linspace()
# parameters are start, stop and the number of elements
# below example will start at 5 and end with 15 and it will generate 8 element, 
# if we dont specify the no of element it will take the default value that is 50

np.linspace(5, 12, 8)

array([ 5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [51]:
# with return steps
# below example take 3.625 steps

lin_array = np.linspace(1, 30, 9, retstep=True)
print(lin_array)

(array([ 1.   ,  4.625,  8.25 , 11.875, 15.5  , 19.125, 22.75 , 26.375,
       30.   ]), 3.625)


In [52]:
lin_array[1]

3.625

# zeros()

In [53]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [54]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## ones()

In [55]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [56]:
# we can also create an ndArray in adding extra pranthesis
# this is 2d array

np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
# this is a three dimensional array
# first parameter 5 specify there will be 5 rows
# second parameter tell that each rows will have 4 row
# third parameter tell each row will have 3 columns

np.ones((5,4,3)) 

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

## eye()

In [58]:
# create 2d array with 1's on the diagonal

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## full()

In [59]:
# create 2x4 2d array with value 4

np.full([2,4], 4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

## empty()

In [60]:
# empty create and empty array with random values

empty_array = np.empty([3,4])
empty_array

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         1.02677907e-308],
       [-2.68156159e+154, -2.68156159e+154,  5.92878775e-323,
         0.00000000e+000]])

In [61]:
np.empty(5)

array([1., 1., 1., 1., 1.])

# copy()

In [62]:
original = np.arange(0,10,2)
original

array([0, 2, 4, 6, 8])

In [63]:
copied = original.copy()
copied

array([0, 2, 4, 6, 8])

## repeat()

In [64]:
# repeat number 2 9 time and output as 1D arary

np.repeat(2, 9)

array([2, 2, 2, 2, 2, 2, 2, 2, 2])

In [65]:
# repeate 2d array 13 times and output as 1D array

rand_array = np.array([[1,2,5], [8,44,2]])
rand_array  = np.repeat(rand_array, 10)
rand_array 

array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  8, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2])

## shape

In [66]:
# return the shape of the array, that is the number of rows and columns

rand_array .shape

(60,)

In [67]:
# empty_array have 3 row and 4 columns

empty_array.shape

(3, 4)

## size

In [68]:
# size will return the number of element in an array

rand_array.size

60

## ndim

In [69]:
# it will return the dimension of the array
# my_1D _array id one dimensional array

my_1D_array.ndim

1

In [70]:
# empty_array si 2D array 

empty_array.ndim

2

## type()

In [71]:
# return the type of array 

type(empty_array)

numpy.ndarray

## dtype()

In [72]:
# return the data type of an array

empty_array.dtype

dtype('float64')

## astype()

In [73]:
empty_array.astype('int32')

array([[          0,           0,           0,           0],
       [          0,           0,           0,           0],
       [-2147483648, -2147483648,           0,           0]], dtype=int32)

## sort()

In [74]:
# sort an array in asceding order

np.sort(my_1D_array)

array([  3,  28,  49,  66, 200])

## info() get information of any function in numpy

In [75]:
np.info(np.full)

 full(shape, fill_value, dtype=None, order='C')

Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, `None`, means
     `np.array(fill_value).dtype`.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.

Returns
-------
out : ndarray
    Array of `fill_value` with the given shape, dtype, and order.

See Also
--------
full_like : Return a new array with shape of input filled with value.
empty : Return a new uninitialized array.
ones : Return a new array setting values to one.
zeros : Return a new array setting values to zero.

Examples
--------
>>> np.full((2, 2), np.inf)
array([[inf, inf],
       [inf, inf]])
>>> np.full((2, 2), 10)
array([[10, 10],
      

In [76]:
np.info(np.eye)

 eye(N, M=None, k=0, dtype=<class 'float'>, order='C')

Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.

    .. versionadded:: 1.14.0

Returns
-------
I : ndarray of shape (N,M)
  An array where all elements are equal to zero, except for the `k`-th
  diagonal, whose values are equal to one.

See Also
--------
identity : (almost) equivalent function
diag : diagonal 2-D array from a 1-D array specified by the user.

Examples
--------
>>> np.eye(2, dt

## random array

In [77]:
# create 1d array with random value

random_array = np.random.rand(10)
random_array

array([0.53690847, 0.50137262, 0.78744109, 0.41961642, 0.09486638,
       0.72888813, 0.0038351 , 0.45448562, 0.70881255, 0.7145263 ])

In [78]:
# create 1d array with random value with size 4

random_int_array = np.random.randint(12, size=4)
random_int_array

array([0, 0, 1, 6])

In [79]:
# create 2d array with random values

np.random.randint(10, size=(2, 3))

array([[8, 8, 0],
       [7, 9, 4]])

## adding and removing element

## append()

In [80]:
to_append = np.array([23,3,1,8])
append_to_this_array = np.arange(8)

In [81]:
# append value right side of 1D array

np.append(append_to_this_array, [12,3,0,44])

array([ 0,  1,  2,  3,  4,  5,  6,  7, 12,  3,  0, 44])

## insert()

In [82]:
to_insert = np.array([23,3,1,8, 34,4]).reshape(3,2)
to_insert

array([[23,  3],
       [ 1,  8],
       [34,  4]])

In [83]:
# insert value a the specific location

np.insert(to_insert,1,[999])

array([ 23, 999,   3,   1,   8,  34,   4])

## delete()

In [84]:
to_delete = np.arange(20).reshape(4,5)
to_delete

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
# delete the second row from the array 

np.delete(to_delete, 1, axis=0)

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [86]:
# delete the element 4 from the array

np.delete(to_delete, 4)

array([ 0,  1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [87]:
# delete the second columns from the array 

np.delete(to_delete, 3, axis=1)

array([[ 0,  1,  2,  4],
       [ 5,  6,  7,  9],
       [10, 11, 12, 14],
       [15, 16, 17, 19]])

## vstack (stack two array  vertically)

In [88]:
# all the input array dimensions for the concatentation axis must match exactly
arr_1 = np.arange(10,20).reshape(2,5)
arr_2 = np.arange(10).reshape(2,5)

np.vstack((arr_1, arr_2))

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

## hstack (stack two array horizontally)

In [89]:

np.hstack((arr_1, arr_2))

array([[10, 11, 12, 13, 14,  0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19,  5,  6,  7,  8,  9]])

# combining and spliting array

## concatenate()

In [90]:
array_one = np.array([[12,4,5], [76,3,4]])
array_two = np.array([[10,34,45], [6,13,44]])

In [91]:
# add array_two as row to end  of array_one

np.concatenate((array_one, array_two), axis=0)

array([[12,  4,  5],
       [76,  3,  4],
       [10, 34, 45],
       [ 6, 13, 44]])

In [92]:
# add array_two as columns to end  of array_one

np.concatenate((array_one, array_two), axis=1)

array([[12,  4,  5, 10, 34, 45],
       [76,  3,  4,  6, 13, 44]])

## split()

In [93]:
# split array into 2 sub array

np.split(array_one,1)

[array([[12,  4,  5],
        [76,  3,  4]])]

## hsplit

In [94]:
split_array = np.arange(20).reshape(5,4)

np.hsplit(split_array,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

## Indexing and Slicing

In [95]:
my_array = np.array([[12, 4, 5],
                     [76, 3 , 4],
                     [0, -5, 7]])
my_array

array([[12,  4,  5],
       [76,  3,  4],
       [ 0, -5,  7]])

In [96]:
my_array[0]

array([12,  4,  5])

In [97]:
my_array[-1]

array([ 0, -5,  7])

In [98]:
my_array[1,2]

4

In [99]:
my_array[1,2] = 12
my_array

array([[12,  4,  5],
       [76,  3, 12],
       [ 0, -5,  7]])

In [100]:
my_array[0:2]

array([[12,  4,  5],
       [76,  3, 12]])

In [101]:
my_array[0:2, 1]

array([4, 3])

In [102]:
my_array[:, 1]

array([ 4,  3, -5])

In [103]:
my_array[my_array < 3]

array([ 0, -5])

In [104]:
my_array[(my_array<14) & (my_array>5)]

array([12, 12,  7])

In [105]:
my_array[~(my_array == 12)]

array([ 4,  5, 76,  3,  0, -5,  7])

## arithmetic operation

In [106]:
a_my_array = np.arange(12)
a_my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [107]:
# add 2 to each array element

np.add(a_my_array, 2)

#or 

a_my_array + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [108]:
# subtract 4 from each array element

np.subtract(a_my_array, 4)

#or

a_my_array - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [109]:
# divide 4 from each array element

np.divide(a_my_array, 4)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75])

In [110]:
# multiply 4 from each array element

np.multiply(a_my_array, 4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44])

In [111]:
# power 2 from each array element

np.power(a_my_array, 2)

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

## operation on two arrays

In [112]:
array_one = np.array([12, 5 , 4])
array_two = np.array([65, 3, 8])

In [113]:
# perform adding on two array element

np.add(array_one, array_two)

array([77,  8, 12])

In [114]:
# perform multiplication on two array element

np.multiply(array_one, array_two)

array([780,  15,  32])

In [115]:
# perform subtraction on two array element

np.subtract(array_one, array_two)

array([-53,   2,  -4])

In [116]:
# perform division on two array element

np.divide(array_one, array_two)

array([0.18461538, 1.66666667, 0.5       ])

In [117]:
# return True if both the element have the same element and shape

np.array_equal(array_one, array_two)

False

In [118]:
# return square root of each element in the array

np.sqrt(array_one)

array([3.46410162, 2.23606798, 2.        ])

In [119]:
# return sin of each element in the array

np.sin(array_one)

array([-0.53657292, -0.95892427, -0.7568025 ])

In [120]:
# get the maximum value from the array

np.max(array_one)

12

In [121]:
# get the minimun value from the array

np.min(array_one)

4

In [122]:
# return the 

np.max(array_one, axis=0)

12

## unique (get the common/unique item from npmpy array)

In [123]:
array_one = np.array([1,2,3,2,3,4,3,4,5,6])
array_two = np.array([7,2,10,2,7,4,9,4,9,8])

# print the unique element from an array
array_one_unique_array = np.unique((array_one))
array_one_unique_array

array([1, 2, 3, 4, 5, 6])

In [124]:
# print the common element from both the arrray
combine_unique_array = np.unique(array_one[array_one == array_two])
combine_unique_array

array([2, 4])

## isin() remove item from array that items exists in another array

In [125]:
 # np.isin to find the common elements (returns an array of Booleans). To filter only False, use ~ 
array_one[~np.isin(array_one, array_two)]

array([1, 3, 3, 3, 5, 6])

## Arthmetic operations on two different 1d array

In [126]:
a_array = np.array([1,2,3,4,0])
b_array = np.array([6,5,5,3,9])

In [127]:
a_array + b_array

array([7, 7, 8, 7, 9])

In [128]:
a_array * b_array

array([ 6, 10, 15, 12,  0])

In [129]:
# this will multiply each element with 10
a_array * 10

array([10, 20, 30, 40,  0])

In [130]:
# to get the product of two array 
a_array @ b_array

43

## replace items that satisfy a condition with another value in numpy array

In [131]:
my_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
my_array[my_array % 2 !=0] = -99
my_array

array([  0, -99,   2, -99,   4, -99,   6, -99,   8, -99])