## Two dimensional arrays

In [183]:
import numpy as np

In [184]:
my_array = np.arange(35)
my_array.shape = (7,5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [185]:
# access the third row 
my_array[2]

array([10, 11, 12, 13, 14])

In [186]:
# we can use negative number for index as well
my_array[-1]

array([30, 31, 32, 33, 34])

In [187]:
# let's access the single element from an array suppose 3rd row 4th column element
row = 2
column = 3
my_array[row, column]

13

In [188]:
# or we can access like this
my_array[2, 3]

13

In [189]:
# or we can access from the element like this
my_array[2][3]

13

In [190]:
# to change the element inside an array
my_array[2,3] = 9999
my_array

array([[   0,    1,    2,    3,    4],
       [   5,    6,    7,    8,    9],
       [  10,   11,   12, 9999,   14],
       [  15,   16,   17,   18,   19],
       [  20,   21,   22,   23,   24],
       [  25,   26,   27,   28,   29],
       [  30,   31,   32,   33,   34]])

## Three Dimensional arrays

In [191]:
# first parameter 3 specify there will be 3 rows inside 3d array
# second parameter tell that each rows will have 7 row
# third parameter tell each row will have 5 columns

my_3D_array = np.arange(105)
my_3D_array.shape = (3, 7, 5)
my_3D_array

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34]],

       [[ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69]],

       [[ 70,  71,  72,  73,  74],
        [ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104]]])

In [192]:
# to access the 2nd 2d-array inside 3d array

my_3D_array[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [193]:
# TO acces the row inside 2d-array

my_3D_array[1, 1]

array([40, 41, 42, 43, 44])

In [194]:
# to access the element inside 2d-array

my_3D_array[1,1,3]

43

In [195]:
# to change the element inside the array

my_3D_array[1,1,3] = 9999
my_3D_array[1]

array([[  35,   36,   37,   38,   39],
       [  40,   41,   42, 9999,   44],
       [  45,   46,   47,   48,   49],
       [  50,   51,   52,   53,   54],
       [  55,   56,   57,   58,   59],
       [  60,   61,   62,   63,   64],
       [  65,   66,   67,   68,   69]])

## Boolean Mask Arrays

In [196]:
# if the element in the array is divisible by 7 then it is mark as true

my_vector = np.array([-17, -4, 0, 2, 21, 37,105])
mode_values = 0 == (my_vector % 7)
mode_values

array([False, False,  True, False,  True, False,  True])

In [197]:
# store all true and false value by comparing with the logical operator

positive_value = mode_values > 0
positive_value

array([False, False,  True, False,  True, False,  True])

In [198]:
# or store all true and false value using the numpy logical_and function

combine_mask = np.logical_and(mode_values, positive_value)
combine_mask

array([False, False,  True, False,  True, False,  True])

In [199]:
# display all the true value

my_vector[combine_mask]

array([  0,  21, 105])

In [200]:
my_vector[positive_value]

array([  0,  21, 105])

In [201]:
# multiple 5 with each element in the array and substract with 2

5 * my_3D_array - 2

array([[[   -2,     3,     8,    13,    18],
        [   23,    28,    33,    38,    43],
        [   48,    53,    58,    63,    68],
        [   73,    78,    83,    88,    93],
        [   98,   103,   108,   113,   118],
        [  123,   128,   133,   138,   143],
        [  148,   153,   158,   163,   168]],

       [[  173,   178,   183,   188,   193],
        [  198,   203,   208, 49993,   218],
        [  223,   228,   233,   238,   243],
        [  248,   253,   258,   263,   268],
        [  273,   278,   283,   288,   293],
        [  298,   303,   308,   313,   318],
        [  323,   328,   333,   338,   343]],

       [[  348,   353,   358,   363,   368],
        [  373,   378,   383,   388,   393],
        [  398,   403,   408,   413,   418],
        [  423,   428,   433,   438,   443],
        [  448,   453,   458,   463,   468],
        [  473,   478,   483,   488,   493],
        [  498,   503,   508,   513,   518]]])

In [202]:
left = np.arange(6).reshape(2,3)
right = np.arange(15).reshape(3,5)
print(left)
print(right)

[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [203]:
# it will give product of the two array

np.dot(left, right)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [204]:
# another simple example of dot

np.dot(2,3)

6

## broadcast operations along axes

In [205]:
# baroadcast pleaase refer -> https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm

my_3D_array

array([[[   0,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14],
        [  15,   16,   17,   18,   19],
        [  20,   21,   22,   23,   24],
        [  25,   26,   27,   28,   29],
        [  30,   31,   32,   33,   34]],

       [[  35,   36,   37,   38,   39],
        [  40,   41,   42, 9999,   44],
        [  45,   46,   47,   48,   49],
        [  50,   51,   52,   53,   54],
        [  55,   56,   57,   58,   59],
        [  60,   61,   62,   63,   64],
        [  65,   66,   67,   68,   69]],

       [[  70,   71,   72,   73,   74],
        [  75,   76,   77,   78,   79],
        [  80,   81,   82,   83,   84],
        [  85,   86,   87,   88,   89],
        [  90,   91,   92,   93,   94],
        [  95,   96,   97,   98,   99],
        [ 100,  101,  102,  103,  104]]])

In [206]:
# to find the sum of all the elements in the array

my_3D_array.sum()

15416

In [207]:
# in this all three 2d arrays that is inside 3d array are added up
my_3D_array.sum(axis = 0)

array([[  105,   108,   111,   114,   117],
       [  120,   123,   126, 10085,   132],
       [  135,   138,   141,   144,   147],
       [  150,   153,   156,   159,   162],
       [  165,   168,   171,   174,   177],
       [  180,   183,   186,   189,   192],
       [  195,   198,   201,   204,   207]])

In [208]:
# when axis = 2 -> inside each 2d array  added up the first column will give -> 105, 
# adding second column will give -> 112 and so on and so forth

my_3D_array.sum(axis = 1)

array([[  105,   112,   119,   126,   133],
       [  350,   357,   364, 10327,   378],
       [  595,   602,   609,   616,   623]])

In [209]:
# when axis = 2 -> inside each 2d array add up all the first row will give -> 10,
# add up all the second row will give -> 35 and so on

my_3D_array.sum(axis = 2)

array([[   10,    35,    60,    85,   110,   135,   160],
       [  185, 10166,   235,   260,   285,   310,   335],
       [  360,   385,   410,   435,   460,   485,   510]])

## Broadcast rule

In [210]:
my_random_2D_array = np.random.random((7, 5))

In [211]:
# numpy is using broadcast rule to check compatibility between 2d array and 3d array to perform arthmetic operations through broadcasting

# set the float value to only tow digit

np.set_printoptions(precision=2)

my_3D_array + my_random_2D_array

array([[[8.14e-01, 1.92e+00, 2.00e+00, 3.51e+00, 4.07e+00],
        [5.69e+00, 6.98e+00, 7.73e+00, 8.19e+00, 9.20e+00],
        [1.02e+01, 1.12e+01, 1.20e+01, 1.40e+01, 1.46e+01],
        [1.58e+01, 1.69e+01, 1.78e+01, 1.86e+01, 1.97e+01],
        [2.02e+01, 2.17e+01, 2.21e+01, 2.31e+01, 2.42e+01],
        [2.55e+01, 2.66e+01, 2.78e+01, 2.89e+01, 2.92e+01],
        [3.05e+01, 3.13e+01, 3.30e+01, 3.34e+01, 3.44e+01]],

       [[3.58e+01, 3.69e+01, 3.70e+01, 3.85e+01, 3.91e+01],
        [4.07e+01, 4.20e+01, 4.27e+01, 1.00e+04, 4.42e+01],
        [4.52e+01, 4.62e+01, 4.70e+01, 4.90e+01, 4.96e+01],
        [5.08e+01, 5.19e+01, 5.28e+01, 5.36e+01, 5.47e+01],
        [5.52e+01, 5.67e+01, 5.71e+01, 5.81e+01, 5.92e+01],
        [6.05e+01, 6.16e+01, 6.28e+01, 6.39e+01, 6.42e+01],
        [6.55e+01, 6.63e+01, 6.80e+01, 6.84e+01, 6.94e+01]],

       [[7.08e+01, 7.19e+01, 7.20e+01, 7.35e+01, 7.41e+01],
        [7.57e+01, 7.70e+01, 7.77e+01, 7.82e+01, 7.92e+01],
        [8.02e+01, 8.12e+01, 8.20e+0

In [212]:
# again numpy is using broadcast rule to check the compatibility between 1d array and 3d array.

one_D_array = np.arange(5) * 2

one_D_array

array([0, 2, 4, 6, 8])

In [213]:
# multiply 1D array with 3D array 

my_3D_array * one_D_array

array([[[    0,     2,     8,    18,    32],
        [    0,    12,    28,    48,    72],
        [    0,    22,    48,    78,   112],
        [    0,    32,    68,   108,   152],
        [    0,    42,    88,   138,   192],
        [    0,    52,   108,   168,   232],
        [    0,    62,   128,   198,   272]],

       [[    0,    72,   148,   228,   312],
        [    0,    82,   168, 59994,   352],
        [    0,    92,   188,   288,   392],
        [    0,   102,   208,   318,   432],
        [    0,   112,   228,   348,   472],
        [    0,   122,   248,   378,   512],
        [    0,   132,   268,   408,   552]],

       [[    0,   142,   288,   438,   592],
        [    0,   152,   308,   468,   632],
        [    0,   162,   328,   498,   672],
        [    0,   172,   348,   528,   712],
        [    0,   182,   368,   558,   752],
        [    0,   192,   388,   588,   792],
        [    0,   202,   408,   618,   832]]])

## flatten()

In [214]:
# Convert 2D array to 1D array

my_random_2D_array.flatten()

array([0.81, 0.92, 0.  , 0.51, 0.07, 0.69, 0.98, 0.73, 0.19, 0.2 , 0.23,
       0.2 , 0.01, 0.99, 0.62, 0.84, 0.87, 0.82, 0.57, 0.74, 0.22, 0.7 ,
       0.12, 0.08, 0.17, 0.49, 0.63, 0.8 , 0.89, 0.16, 0.51, 0.29, 0.97,
       0.43, 0.36])

## T (transpose)

In [215]:
reverse = np.arange(10).reshape(2,5)
reverse

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [216]:
# replace row to column and columns to row

reverse.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

## reshape()

In [217]:
reverse.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])